[package]
name = "project"
version = "0.1.0"
authors = ["sigilante"]
description = "Bitcoin on Nock ISA-based systems experiment."
license = "MIT"

template = "http-server"
template-commit = "5039878a77b1ec4e42e4e56fb95f3aa63398ce49"

[dependencies]
"urbit/zuse"   = "@k409"
"nockchain/zose" = "latest"

[dependencies.sequent]
git = "https://github.com/jackfoxy/sequent"
commit = "7fc95fd4d6df7548cf354c9c91df2980e902770d"
path = "desk"
files = ["lib/seq"]
